/* empty css                      */import{S as g,A as h,P as w}from"./assets/vendor-iT9SqOa9.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();let f=null;function y(){window.innerWidth<1440&&!f&&(f=new g(".mySwiper",{modules:[h,w],slidesPerView:1.2,spaceBetween:16,autoplay:{delay:2500,disableOnInteraction:!1},loop:!0,pagination:{el:".swiper-pagination",clickable:!0,renderBullet:function(i,n){return`<span class="${n}">
                    <span class="dot"></span>
                  </span>`}}}))}function v(){window.innerWidth>=1440&&f&&(f.destroy(!0,!0),f=null)}function m(){window.innerWidth<1440?y():v()}m();window.addEventListener("resize",m);document.querySelectorAll(".faq-acc-el-trigger").forEach(i=>{i.addEventListener("click",()=>{const n=i.closest(".faq-acc-el"),r=n.querySelector(".faq-acc-el-descr-frame");n.classList.contains("open")?(n.classList.remove("open"),r.style.maxHeight="0"):(n.classList.add("open"),r.style.maxHeight=r.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector(".menu-button"),n=i.querySelector(".icon"),r=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 6H19M5 18H19M5 12H19" stroke="#EEEEEE" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#EEEEEE" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;i.addEventListener("click",()=>{t=!t,n.innerHTML=t?o:d,t?s():c()}),a.forEach(u=>u.addEventListener("click",()=>{c(),n.innerHTML=d,t=!1})),window.addEventListener("scroll",l);function s(){r.style.display="block"}function c(){r.style.display="none"}function l(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function i(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const s=document.getElementById(o);if(!s)return;const c=i(),l=s.getBoundingClientRect().top+window.pageYOffset-c;window.scrollTo({top:l,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(s){const c=this.getAttribute("href");if(!c)return;const[l,u]=c.split("#");if(!u)return;const p=window.location.pathname.split("/").pop();!(l===""||l==="./"||l===p||l==="./"+p)||!document.getElementById(u)||(s.preventDefault(),n(u),t(u))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(c=>c.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${o}"]`);s&&s.closest(".navigation-item").classList.add("active")}function d(){const o=window.pageYOffset+i()+100;a.forEach(s=>{const c=s.offsetTop,l=c+s.offsetHeight;o>=c&&o<l&&t(s.id)})}if(window.addEventListener("scroll",d),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{n(o),t(o)},300)}});document.addEventListener("DOMContentLoaded",function(){const i=document.getElementById("cookie-popup"),n=document.getElementById("accept-cookies"),r=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(i.style.display="block"),n.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),i.style.display="none"}),r.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),i.style.display="none"})});
//# sourceMappingURL=index.js.map
